apiVersion: v1
kind: Service
metadata:
    name: turbine-server-gateway
    labels:
        app: turbine-server
        tier: metrics
spec:
    type: LoadBalancer
    ports:
    - port: 1113
    selector:
        app: turbine-server
        tier: metrics


