apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
    name: turbine-server
spec:
    replicas: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    minReadySeconds: 5
    template:
        metadata:
            labels:
              app: turbine-server
              tier: metrics
        spec:
            containers:
            - name: turbine-server
              image: sleepingtalent/turbine-server:1.0.17-RC
              env:
              - name: CONFIG_URL
                value: http://a7248fd52b28911e798ab0a429a68c51-925490504.eu-west-1.elb.amazonaws.com:1111/config-api/
              ports:
              - containerPort: 1113

---

kind: Service
metadata:
    name: turbine-server-gateway
    labels:
        app: turbine-server
        tier: metrics
spec:
    type: LoadBalancer
    ports:
    - port: 1113
    selector:
        app: turbine-server
        tier: metrics


